import { Request, Response } from "express";

// GET /classify_tickets
export function handleClassifyTickets(req: Request, res: Response) {
  // This is where your backend logic will go
  // For now, sending a placeholder response to indicate the endpoint exists
  res.json({
    ticket_categories: [
      {
        category: "Rate",
        total_catalysts: 2,
        catalysts: [
          {
            catalyst: "Negotiation",
            total_tickets: 4,
            tickets: [
              {
                id: "1234567890",
                url: "https://example.com/ticket/1234567890.json",
                Subject: "Rate increase negotiation for Q2 projects",
                Description: "Requesting rate adjustment based on experience and market conditions",
                channel: "email",
                from_address: "michael.rodriguez@glg.com",
                created_at: "2024-01-14T11:15:00Z",
                updated_at: "2024-01-16T10:45:00Z",
                priority: "high",
                ticket_language: "en",
                medium: "nmhome",
                network_member_id: 123456789
              }
            ]
          }
        ]
      }
    ]
  });
}

// GET /ticket_details/:ticketId
export function handleTicketDetails(req: Request, res: Response) {
  const { ticketId } = req.params;
  
  // This is where your backend logic will go
  // For now, sending a placeholder response to indicate the endpoint exists
  res.json({
    ticket_details: {
      id: ticketId,
      linked_network_member_id: 123456789,
      network_member_details: {
        NAME: "Sarah Chen",
        LOCALIZED_NAME: "陈莎拉",
        COUNTRY: "United States",
        ADDRESS: "123 Business Ave",
        CITY: "New York",
        STATE: "NY",
        ZIP: "10001",
        REGION: "North America",
        PHONE: "+1-555-0123",
        EMAIL: "sarah.chen@glg.com",
        TERMS_CONDITIONS_ACTIVE: "true",
        LATEST_TERMS_CONDITIONS_START_DATE: "2024-01-01",
        DAILY_RATE: "1200.0000",
        CONSULTATION_RATE: "350.0000",
        MIN_PROJECT_AMOUNT: "5000",
        RECOMMENDED_CONSULTATION_RATE: "300.0000",
        BIOGRAPHY: "Sarah Chen is a seasoned healthcare consultant with over 8 years of experience in digital transformation initiatives.",
        COUNCIL_NAME: "Healthcare & Life Sciences",
        PRACTICE_AREA: "Healthcare Analytics",
        IS_DNC: "false",
        DNC_REASON: "UNKNOWN",
        CURRENTLY_RETIRED: "false",
        PREFERRED_CULTURE: "en",
        CURRENT_PRIMARY_LANGUAGE: "English",
        PROFILE_CREATE_DATE: "2022-03-15",
        NPI_NUMBER: "1234567890",
        LINKED_IN_PROFILE_URL: "https://linkedin.com/in/sarahchen",
        PUBLIC_OFFICIAL_IND: "false",
        PERSONA_VERIFICATION_DATE: "2024-01-01"
      },
      sections: [
        {
          title: "Work History",
          summary: "Current Senior Healthcare Consultant at GLG with 8+ years experience.",
          details: {
            network_member_id: 123456789,
            history: []
          }
        }
      ]
    }
  });
}

// POST /generate_auto_response
export function handleGenerateAutoResponse(req: Request, res: Response) {
  const { ticket_id, ticket_subject, ticket_description, category, catalyst, ticket_details } = req.body;
  
  // This is where your backend logic will go
  // For now, sending a placeholder response to indicate the endpoint exists
  const htmlContent = `
    <div style="font-family: Arial, sans-serif; max-width: 600px; margin: 0 auto; padding: 20px; background-color: #ffffff;">
      <div style="border-bottom: 3px solid #1E3A8A; padding-bottom: 20px; margin-bottom: 30px;">
        <h1 style="color: #1E3A8A; margin: 0; font-size: 24px;">GLG Response - ${category} ${catalyst}</h1>
        <p style="color: #6B7280; margin: 5px 0 0 0; font-size: 14px;">Ticket #${ticket_id} - ${ticket_subject}</p>
        <p style="color: #6B7280; margin: 5px 0 0 0; font-size: 12px;">Automated response generated by MIRA</p>
      </div>
      <div style="margin-bottom: 25px;">
        <p style="color: #374151; line-height: 1.6; margin: 0 0 15px 0;">Dear ${ticket_details.network_member_details.NAME},</p>
        <p style="color: #374151; line-height: 1.6; margin: 0 0 15px 0;">
          Thank you for your ${category.toLowerCase()} ${catalyst.toLowerCase()} request: "${ticket_subject}".
          We have processed your request successfully.
        </p>
      </div>
    </div>
  `;

  res.json({
    generated_auto_response: htmlContent.trim()
  });
}
